apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mavenwebapp
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp     # Pod Labels
  template:                # POD template
    metadata:
      labels:
        app: mavenwebapp   # Pod Labels
    spec:
      containers: 
      - name: mavenwebapp  # Container name
        image: rahultechmumbai/maven-web-app:TAG  # Image name
        ports:
        - containerPort: 8080   # Container Port
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappcsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:           # POD Label as selector
    app: mavenwebapp
  ports:
  - port: 80          # The port exposed by the service
    targetPort: 8080  # The port that the pods are listening on
#    nodePort: 30080  # The NodePort; choose a value within the range 30000-32767        

